### ISSUE TITLE
After Installation Stores > Configuration > Sales > Tax Section displays blank in Magento 2.1

### ISSUE THREAD

**Issue by sonimanthan228** [classyllama/ClassyLlama_AvaTax#45] opened 2016-12-06 06:35 UTC
I have installed a extension perfectly and also clear cache. store > configuration > sales > tax section display blanks and when I uninstall extension,TAX configuration section works perfectly.Anybody else face this issue ? Please help on this issue.Any need changes ?

**Comment by erikhansen** [comment] 2016-12-06 16:21
@sonimanthan228 We have many merchants using this extension on 2.1.x and none have reported this issue. My expectation is that there is something going on in your environment that is causing this error.

You should look at your PHP/Nginx/Apache error logs after trying to load the *store > configuration > sales > tax section* page to try an identify the cause of the error.

Make sure you've flushed the cache after installing the extension. If the site is running in production mode, make sure to recompile DI and static-content.

**Comment by erikhansen** [comment] 2016-12-29 04:27
Closing this issue unless steps are provided to reproduce the issue.

**Closed by erikhansen** 2016-12-29 04:27 UTC
