### ISSUE TITLE
Shipping save processor should be modified to include new payload extender

### ISSUE THREAD

**Issue by loganstellway** [classyllama/ClassyLlama_AvaTax#167] opened 2018-08-27 23:53 UTC
There was a commit ([0da089d](https://github.com/magento/magento2/commit/0da089d0a662d3da69200ec84e108c09a85339c2)) added to the Magento `2.2.2` release that adds a payload extender for the checkout shipping save processor. 

The extender adds a reference to a new JavaScript component that provides an easy entry point for third-party modules to plugin and manipulate the shipping information payload. 

Here is a reference to the [original pull request](https://github.com/magento/magento2/pull/10991) for more information. 

(* It didn't seem appropriate to format this issue with the template.. I hope it's okay that I didn't)

**Comment by rsisco** [comment] 2018-10-16 14:38
Closing as a duplicate of issue #181 - closing this issue since the other one includes more detail.

**Closed by rsisco** 2018-10-16 14:38 UTC
