### ISSUE TITLE
Getting error message SSL: Connection reset by peer in /vendor/avalara/avatax/AvaTax/DynamicSoapClient.php on line 34

### ISSUE THREAD

**Issue by pioneerathletics** [classyllama/ClassyLlama_AvaTax#119] opened 2018-04-09 17:44 UTC
### Preconditions

1. Magento 2.1.12
2. Avatax version 1.3.5

### Steps to reproduce

1. I upgraded to 2.1.12 over the weekend with no issues
2. Today I turned on sign static files and I was getting an error code in checkout saying it could not be completed
3. This is the error code when I try to reconnect to Avatax SSL: Connection reset by peer in /vendor/avalara/avatax/AvaTax/DynamicSoapClient.php on line 34

### Expected result

1. 

### Actual result

1. SSL: Connection reset by peer in /vendor/avalara/avatax/AvaTax/DynamicSoapClient.php on line 34

**Comment by rsisco** [comment] 2018-04-12 15:55
@pioneerathletics - I am unable to reproduce this issue on my local installation. Can you try to reproduce the issue on a new vanilla install of Magento 2?

**Comment by rsisco** [comment] 2018-04-12 18:05
@pioneerathletics - This could absolutely be a network connectivity issue. If I understand correctly, you are no longer having this problem, so I am going to go ahead and close this issue.

**Closed by rsisco** 2018-04-12 18:05 UTC
