### ISSUE TITLE
Class ClassyLlama\AvaTax\Framework\Interaction\TaxCalculation\Proxy does not exist

### ISSUE THREAD

**Issue by vijay-wagento** [classyllama/ClassyLlama_AvaTax#42] opened 2016-12-01 10:35 UTC
Above error throws when I am creating customer

**Comment by erikhansen** [comment] 2016-12-02 18:14
@vijay-wagento We are not able to reproduce this issue locally.

Can you provide steps for reproducing this issue from a clean install of Magento 2.1.2 with sample data? Please also provide details about your environment such as:

1. Version of PHP being used
2. Please determine whether this is reproducible in development mode AND production mode, or just one of those modes
3. Whether customer is being created in the backend or frontend

**Comment by erikhansen** [comment] 2016-12-29 04:28
Closing this issue unless steps are provided to reproduce the issue.

**Closed by erikhansen** 2016-12-29 04:28 UTC

**Comment by ionutdicu** [comment] 2018-01-07 21:18
Make sure the Avalara AvaTax PHP library is installed as the module depends on it: 
composer require avalara/avatax
Read: https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#installation

**Comment by erikhansen** [comment] 2018-01-07 23:21
@ionutdicu Thanks for your tip. If you use Composer to install this extension, the `avalara/avatax` package should be automatically downloaded since it's included in the [composer.json](https://github.com/classyllama/ClassyLlama_AvaTax/blob/develop/composer.json#L8) "require" section. Because of this, you should not have to run `composer require avalara/avatax`. 

However you are correct that the absence of that library is what will cause the `Class ClassyLlama\AvaTax\Framework\Interaction\TaxCalculation\Proxy does not exist` error. That's why in the [Install by copying files](https://www.classyllama.com/documentation/extensions/avatax-magento-2-module#install-by-copying-files) section of the documentation, we added explicit information about ensuring that extension was installed.

**Comment by lewis-dan** [comment] 2019-02-13 15:54
@ionutdicu Please run composer require avalara/avatax at your magento Root, it will ask repo.magento username and password. Once you provide that, it will install without any error. If you face any other issue, please feel free to contact me.
