### ISSUE TITLE
jquery.js:9218 Uncaught TypeError: require.exec is not a function

### ISSUE THREAD

**Issue by expandlab** [classyllama/ClassyLlama_AvaTax#25] opened 2016-07-12 21:10 UTC
Running the latest version (3.0.1) and getting this error on the address save of the customer dashboard.

`jquery.js:9218 Uncaught TypeError: require.exec is not a function`

I've done a series of stack watches and getting closer.  Appears to be occurring somewhere around this line.  I've got to head out for the day, but hopefully you guys have a quick fix?

```
address-validation-modal.js:99
addressValidationForm.fillValidateForm(self.validationContainer);
```

**Comment by erikhansen** [comment] 2016-07-13 22:38
@expandlab I was not able to reproduce on a clean Magento 2.1 install with sample data. Can you provide exact steps to reproduce? I did find another issue related to customer addresses that I just logged: https://github.com/classyllama/ClassyLlama_AvaTax/issues/27 See that issue for an example of how to best provide steps to reproduce.

**Comment by erikhansen** [comment] 2016-07-20 20:14
@expandlab Can you provide me steps to reproduce? If not, I'll be closing this issue.

**Comment by erikhansen** [comment] 2016-07-21 20:03
Closing until and unless we get steps to reproduce.

**Closed by erikhansen** 2016-07-21 20:03 UTC

**Comment by Niranjan2016** [comment] 2017-01-20 07:02
Hi,
I am facing same error. Following are the details when the error occurs on Magento 2.1.
1. created a custom module page.
2. removed every block from custom module page except content block.
3. In other page wrote a $.get to pull the custom page via ajax.
4. finally trying to add the result received from the $.get call to a div using $("#mydiv").html(result);
5. And $("#mydiv").html(result); statement is where the error is occuring.

can you reopen this and verify pls?
Thanks
